### ISSUE TITLE
Missing "product" and "vendor" fields in the interfaces object

### ISSUE THREAD

**Issue by bdha** [joyent/dcim_agent#4]
Need something like:

```
"product": "82599ES 10-Gigabit SFI/SFP+ Network Connection",
"state": "up",
"vendor": "Intel" 
```                                                      

If it's a virtual interface, like external0, set product to "Crossbow VNIC' and "vendor" to "illumos"?

If it's ipmi1 the product should be "OOB" and vendor "Intel."

**Comment by bdelano** [comment]
added the defaults suggested... if there is a way to pull this information from the node just let me know
